version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: app
    env_file: .env
    depends_on:
      - postgres

volumes:
  pg_data:
    driver: local 
    driver_opts:
      type: none
      device: ${PWD}/pg_data
      o: bind