from sqlalchemy import Column, String, DateTime, Float, Boolean, ARRAY
from db import Base

class Vulnerability(Base):
    __tablename__ = "vulnerabilities"

    cve_id = Column(String, primary_key=True, index=True)
    description = Column(String)
    url = Column(String, nullable=True)
    published_date = Column(DateTime)
    last_modified_date = Column(DateTime)
    score = Column(Float)
    severity = Column(String)
    weaknesses = Column(ARRAY(String), nullable=True)
    references = Column(ARRAY(String), nullable=True)
    v31score = Column(Float, nullable=True)
    v30score = Column(Float, nullable=True)
    v2score = Column(Float, nullable=True)
    cvssV2Severity = Column(String, nullable=True)
    cvssV3Severity = Column(String, nullable=True)
    has_cert_alerts = Column(Boolean, nullable=True)
    has_cert_notes = Column(Boolean, nullable=True)
    has_kev = Column(Boolean, nullable=True)
    v31impactScore = Column(Float, nullable=True)
    v30impactScore = Column(Float, nullable=True)
    v2impactScore = Column(Float, nullable=True)
    v31exploitability = Column(Float, nullable=True)
    v2exploitability = Column(Float, nullable=True)
    v31attackVector = Column(String, nullable=True)
    v2accessVector = Column(String, nullable=True)
    v31attackComplexity = Column(String, nullable=True)
    v2accessComplexity = Column(String, nullable=True)
    v31privilegesRequired = Column(String, nullable=True)
    v31userInteraction = Column(String, nullable=True)
    v31scope = Column(String, nullable=True)
    v31confidentialityImpact = Column(String, nullable=True)
    v2authentication = Column(String, nullable=True)
    v2confidentialityImpact = Column(String, nullable=True)
    v31integrityImpact = Column(String, nullable=True)
    v2integrityImpact = Column(String, nullable=True)
    v31availabilityImpact = Column(String, nullable=True)
    v2availabilityImpact = Column(String, nullable=True)